import csv

# Dummy data for bus stop distances and times
data = [
    {"From": "Palika Kendra", "To": "Tolstoy Marg", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Palika Kendra", "To": "Regal", "Distance (km)": 1.2, "Time (minutes)": 8},
    {"From": "Palika Kendra", "To": "Scindia House", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Palika Kendra", "To": "Shivaji Stadium", "Distance (km)": 1.8, "Time (minutes)": 10},
    {"From": "Tolstoy Marg", "To": "Regal", "Distance (km)": 0.7, "Time (minutes)": 4},
    {"From": "Tolstoy Marg", "To": "Scindia House", "Distance (km)": 1.3, "Time (minutes)": 9},
    {"From": "Tolstoy Marg", "To": "Shivaji Stadium", "Distance (km)": 2.1, "Time (minutes)": 12},
    {"From": "Regal", "To": "Scindia House", "Distance (km)": 0.6, "Time (minutes)": 3},
    {"From": "Regal", "To": "Shivaji Stadium", "Distance (km)": 1.5, "Time (minutes)": 7},
    {"From": "Scindia House", "To": "Shivaji Stadium", "Distance (km)": 1.1, "Time (minutes)": 6},
    {"From": "INA Colony", "To": "AIIMS", "Distance (km)": 0.5, "Time (minutes)": 4},
    {"From": "INA Colony", "To": "Safdarjung Terminal", "Distance (km)": 1.2, "Time (minutes)": 8},
    {"From": "INA Colony", "To": "Kidwai Nagar", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "INA Colony", "To": "Lodhi Colony", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "AIIMS", "To": "Safdarjung Terminal", "Distance (km)": 0.7, "Time (minutes)": 5},
    {"From": "AIIMS", "To": "Kidwai Nagar", "Distance (km)": 0.9, "Time (minutes)": 6},
    {"From": "AIIMS", "To": "Lodhi Colony", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Safdarjung Terminal", "To": "Kidwai Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Safdarjung Terminal", "To": "Lodhi Colony", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Kidwai Nagar", "To": "Lodhi Colony", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Town Hall", "To": "St. Stephen's Church", "Distance (km)": 0.6, "Time (minutes)": 4},
    {"From": "Town Hall", "To": "Red Fort", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Town Hall", "To": "Kashmere Gate", "Distance (km)": 1.8, "Time (minutes)": 10},
    {"From": "Town Hall", "To": "Old Delhi Railway Station", "Distance (km)": 1.2, "Time (minutes)": 8},
    {"From": "St. Stephen's Church", "To": "Red Fort", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "St. Stephen's Church", "To": "Kashmere Gate", "Distance (km)": 1.5, "Time (minutes)": 8},
    {"From": "St. Stephen's Church", "To": "Old Delhi Railway Station", "Distance (km)": 1.3, "Time (minutes)": 7},
    {"From": "Red Fort", "To": "Kashmere Gate", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Red Fort", "To": "Old Delhi Railway Station", "Distance (km)": 1.6, "Time (minutes)": 9},
    {"From": "Kashmere Gate", "To": "Old Delhi Railway Station", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "ISBT Kashmere Gate", "To": "Mori Gate Terminal", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "ISBT Kashmere Gate", "To": "Shakti Nagar", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "ISBT Kashmere Gate", "To": "Tis Hazari Court", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "ISBT Kashmere Gate", "To": "Civil Lines", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Mori Gate Terminal", "To": "Shakti Nagar", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Mori Gate Terminal", "To": "Tis Hazari Court", "Distance (km)": 0.9, "Time (minutes)": 6},
    {"From": "Mori Gate Terminal", "To": "Civil Lines", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Shakti Nagar", "To": "Tis Hazari Court", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Shakti Nagar", "To": "Civil Lines", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Tis Hazari Court", "To": "Civil Lines", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "New Delhi Railway Station Gate 1", "To": "Ajmeri Gate", "Distance (km)": 0.6, "Time (minutes)": 4},
    {"From": "New Delhi Railway Station Gate 1", "To": "JLN Marg", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "New Delhi Railway Station Gate 1", "To": "Kamla Market", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "New Delhi Railway Station Gate 1", "To": "CP New Delhi", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Ajmeri Gate", "To": "JLN Marg", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Ajmeri Gate", "To": "Kamla Market", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Ajmeri Gate", "To": "CP New Delhi", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "JLN Marg", "To": "Kamla Market", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "JLN Marg", "To": "CP New Delhi", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Kamla Market", "To": "CP New Delhi", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Huda City Centre Terminal", "To": "IFFCO Chowk", "Distance (km)": 1.2, "Time (minutes)": 8},
    {"From": "Huda City Centre Terminal", "To": "Sector 29", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Huda City Centre Terminal", "To": "Sector 44", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Huda City Centre Terminal", "To": "Sushant Lok", "Distance (km)": 2.0, "Time (minutes)": 12},
    {"From": "IFFCO Chowk", "To": "Sector 29", "Distance (km)": 0.9, "Time (minutes)": 6},
    {"From": "IFFCO Chowk", "To": "Sector 44", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "IFFCO Chowk", "To": "Sushant Lok", "Distance (km)": 1.6, "Time (minutes)": 9},
    {"From": "Sector 29", "To": "Sector 44", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Sector 29", "To": "Sushant Lok", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Sector 44", "To": "Sushant Lok", "Distance (km)": 1.2, "Time (minutes)": 8},
    {"From": "Rajendra Place Bus Stop", "To": "Shanker Road", "Distance (km)": 0.7, "Time (minutes)": 5},
    {"From": "Rajendra Place Bus Stop", "To": "Patel Nagar", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Rajendra Place Bus Stop", "To": "East Patel Nagar", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Rajendra Place Bus Stop", "To": "Pusa Road", "Distance (km)": 1.8, "Time (minutes)": 10},
    {"From": "Shanker Road", "To": "Patel Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Shanker Road", "To": "East Patel Nagar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Shanker Road", "To": "Pusa Road", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Patel Nagar", "To": "East Patel Nagar", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Patel Nagar", "To": "Pusa Road", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "East Patel Nagar", "To": "Pusa Road", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Lajpat Nagar Market", "To": "Lajpat Nagar Bus Terminal", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Lajpat Nagar Market", "To": "Ring Road", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Lajpat Nagar Market", "To": "Moolchand", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Lajpat Nagar Market", "To": "Defence Colony", "Distance (km)": 1.7, "Time (minutes)": 10},
    {"From": "Lajpat Nagar Bus Terminal", "To": "Ring Road", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Lajpat Nagar Bus Terminal", "To": "Moolchand", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Lajpat Nagar Bus Terminal", "To": "Defence Colony", "Distance (km)": 1.6, "Time (minutes)": 9},
    {"From": "Ring Road", "To": "Moolchand", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Ring Road", "To": "Defence Colony", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Moolchand", "To": "Defence Colony", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Karol Bagh Metro Station Bus Stop", "To": "Jhandewalan", "Distance (km)": 0.6, "Time (minutes)": 4},
    {"From": "Karol Bagh Metro Station Bus Stop", "To": "Pusa Road", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Karol Bagh Metro Station Bus Stop", "To": "Rajender Nagar", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Karol Bagh Metro Station Bus Stop", "To": "Karol Bagh Market", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Jhandewalan", "To": "Pusa Road", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Jhandewalan", "To": "Rajender Nagar", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Jhandewalan", "To": "Karol Bagh Market", "Distance (km)": 1.7, "Time (minutes)": 10},
    {"From": "Pusa Road", "To": "Rajender Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Pusa Road", "To": "Karol Bagh Market", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Rajender Nagar", "To": "Karol Bagh Market", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Saket Metro Station Bus Stop", "To": "Malviya Nagar", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Saket Metro Station Bus Stop", "To": "Select Citywalk", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Saket Metro Station Bus Stop", "To": "Pushp Vihar", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Saket Metro Station Bus Stop", "To": "Saket District Centre", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Malviya Nagar", "To": "Select Citywalk", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Malviya Nagar", "To": "Pushp Vihar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Malviya Nagar", "To": "Saket District Centre", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Select Citywalk", "To": "Pushp Vihar", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Select Citywalk", "To": "Saket District Centre", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Pushp Vihar", "To": "Saket District Centre", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Sikanderpur Metro Station Bus Stop", "To": "Guru Dronacharya", "Distance (km)": 0.7, "Time (minutes)": 5},
    {"From": "Sikanderpur Metro Station Bus Stop", "To": "DLF Phase 2", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Sikanderpur Metro Station Bus Stop", "To": "M G Road", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Sikanderpur Metro Station Bus Stop", "To": "Arjun Marg", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Guru Dronacharya", "To": "DLF Phase 2", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Guru Dronacharya", "To": "M G Road", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Guru Dronacharya", "To": "Arjun Marg", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "DLF Phase 2", "To": "M G Road", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "DLF Phase 2", "To": "Arjun Marg", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "M G Road", "To": "Arjun Marg", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Noida City Centre Terminal", "To": "Sector 34", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Noida City Centre Terminal", "To": "Sector 50", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Noida City Centre Terminal", "To": "Sector 39", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Noida City Centre Terminal", "To": "Noida Stadium", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Sector 34", "To": "Sector 50", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Sector 34", "To": "Sector 39", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Sector 34", "To": "Noida Stadium", "Distance (km)": 1.6, "Time (minutes)": 9},
    {"From": "Sector 50", "To": "Sector 39", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Sector 50", "To": "Noida Stadium", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Sector 39", "To": "Noida Stadium", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Botanical Garden Metro Station Bus Stop", "To": "Sector 37", "Distance (km)": 0.7, "Time (minutes)": 5},
    {"From": "Botanical Garden Metro Station Bus Stop", "To": "Sector 44", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Botanical Garden Metro Station Bus Stop", "To": "NTPC", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Botanical Garden Metro Station Bus Stop", "To": "Amity University", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Sector 37", "To": "Sector 44", "Distance (km)": 0.9, "Time (minutes)": 6},
    {"From": "Sector 37", "To": "NTPC", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Sector 37", "To": "Amity University", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Sector 44", "To": "NTPC", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Sector 44", "To": "Amity University", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "NTPC", "To": "Amity University", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Vishwavidyalaya Metro Station Bus Stop", "To": "University of Delhi", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Vishwavidyalaya Metro Station Bus Stop", "To": "Guru Tegh Bahadur Nagar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Vishwavidyalaya Metro Station Bus Stop", "To": "Kamla Nagar", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Vishwavidyalaya Metro Station Bus Stop", "To": "Mall Road", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "University of Delhi", "To": "Guru Tegh Bahadur Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "University of Delhi", "To": "Kamla Nagar", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "University of Delhi", "To": "Mall Road", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Guru Tegh Bahadur Nagar", "To": "Kamla Nagar", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Guru Tegh Bahadur Nagar", "To": "Mall Road", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Kamla Nagar", "To": "Mall Road", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Janakpuri West Metro Station Bus Stop", "To": "District Centre", "Distance (km)": 0.6, "Time (minutes)": 4},
    {"From": "Janakpuri West Metro Station Bus Stop", "To": "Tilak Nagar", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Janakpuri West Metro Station Bus Stop", "To": "Uttam Nagar", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Janakpuri West Metro Station Bus Stop", "To": "Vikas Puri", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "District Centre", "To": "Tilak Nagar", "Distance (km)": 0.9, "Time (minutes)": 6},
    {"From": "District Centre", "To": "Uttam Nagar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "District Centre", "To": "Vikas Puri", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Tilak Nagar", "To": "Uttam Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Tilak Nagar", "To": "Vikas Puri", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Uttam Nagar", "To": "Vikas Puri", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Anand Vihar ISBT", "To": "Vivek Vihar", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Anand Vihar ISBT", "To": "Karkardooma", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Anand Vihar ISBT", "To": "Preet Vihar", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Anand Vihar ISBT", "To": "Patparganj", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Vivek Vihar", "To": "Karkardooma", "Distance (km)": 0.7, "Time (minutes)": 4},
    {"From": "Vivek Vihar", "To": "Preet Vihar", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Vivek Vihar", "To": "Patparganj", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Karkardooma", "To": "Preet Vihar", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Karkardooma", "To": "Patparganj", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Preet Vihar", "To": "Patparganj", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Nehru Place Metro Station Bus Stop", "To": "Kalkaji", "Distance (km)": 0.7, "Time (minutes)": 4},
    {"From": "Nehru Place Metro Station Bus Stop", "To": "CR Park", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Nehru Place Metro Station Bus Stop", "To": "GK-2", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Nehru Place Metro Station Bus Stop", "To": "East of Kailash", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Kalkaji", "To": "CR Park", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Kalkaji", "To": "GK-2", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Kalkaji", "To": "East of Kailash", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "CR Park", "To": "GK-2", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "CR Park", "To": "East of Kailash", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "GK-2", "To": "East of Kailash", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Sadar Bazar Bus Stop", "To": "Sadar Bazar", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Sadar Bazar Bus Stop", "To": "Roop Nagar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Sadar Bazar Bus Stop", "To": "Subzi Mandi", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Sadar Bazar Bus Stop", "To": "Pul Bangash", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Sadar Bazar", "To": "Roop Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Sadar Bazar", "To": "Subzi Mandi", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Sadar Bazar", "To": "Pul Bangash", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Roop Nagar", "To": "Subzi Mandi", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Roop Nagar", "To": "Pul Bangash", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Subzi Mandi", "To": "Pul Bangash", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Sadar Bazar", "To": "Roop Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Sadar Bazar", "To": "Subzi Mandi", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Sadar Bazar", "To": "Pul Bangash", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Roop Nagar", "To": "Subzi Mandi", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Roop Nagar", "To": "Pul Bangash", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Subzi Mandi", "To": "Pul Bangash", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Sector 29", "To": "Huda City Centre", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "IFFCO Chowk", "To": "Sushant Lok", "Distance (km)": 1.6, "Time (minutes)": 9},
    {"From": "Sector 29", "To": "Sector 44", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Sector 29", "To": "Sushant Lok", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Sector 44", "To": "Sushant Lok", "Distance (km)": 1.2, "Time (minutes)": 8},
    {"From": "Rajendra Place Bus Stop", "To": "Shanker Road", "Distance (km)": 0.7, "Time (minutes)": 5},
    {"From": "Rajendra Place Bus Stop", "To": "Patel Nagar", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Rajendra Place Bus Stop", "To": "East Patel Nagar", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Rajendra Place Bus Stop", "To": "Pusa Road", "Distance (km)": 1.8, "Time (minutes)": 10},
    {"From": "Shanker Road", "To": "Patel Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Shanker Road", "To": "East Patel Nagar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Shanker Road", "To": "Pusa Road", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Patel Nagar", "To": "East Patel Nagar", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Patel Nagar", "To": "Pusa Road", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "East Patel Nagar", "To": "Pusa Road", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Lajpat Nagar Market", "To": "Lajpat Nagar Bus Terminal", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Lajpat Nagar Market", "To": "Ring Road", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Lajpat Nagar Market", "To": "Moolchand", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Lajpat Nagar Market", "To": "Defence Colony", "Distance (km)": 1.7, "Time (minutes)": 10},
    {"From": "Lajpat Nagar Bus Terminal", "To": "Ring Road", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Lajpat Nagar Bus Terminal", "To": "Moolchand", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Lajpat Nagar Bus Terminal", "To": "Defence Colony", "Distance (km)": 1.6, "Time (minutes)": 9},
    {"From": "Ring Road", "To": "Moolchand", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Ring Road", "To": "Defence Colony", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Moolchand", "To": "Defence Colony", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Karol Bagh Metro Station Bus Stop", "To": "Jhandewalan", "Distance (km)": 0.6, "Time (minutes)": 4},
    {"From": "Karol Bagh Metro Station Bus Stop", "To": "Pusa Road", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Karol Bagh Metro Station Bus Stop", "To": "Rajender Nagar", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Karol Bagh Metro Station Bus Stop", "To": "Karol Bagh Market", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Jhandewalan", "To": "Pusa Road", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Jhandewalan", "To": "Rajender Nagar", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Jhandewalan", "To": "Karol Bagh Market", "Distance (km)": 1.7, "Time (minutes)": 10},
    {"From": "Pusa Road", "To": "Rajender Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Pusa Road", "To": "Karol Bagh Market", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Rajender Nagar", "To": "Karol Bagh Market", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Saket Metro Station Bus Stop", "To": "Malviya Nagar", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Saket Metro Station Bus Stop", "To": "Select Citywalk", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Saket Metro Station Bus Stop", "To": "Pushp Vihar", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Saket Metro Station Bus Stop", "To": "Saket District Centre", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Malviya Nagar", "To": "Select Citywalk", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Malviya Nagar", "To": "Pushp Vihar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Malviya Nagar", "To": "Saket District Centre", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Select Citywalk", "To": "Pushp Vihar", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Select Citywalk", "To": "Saket District Centre", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Pushp Vihar", "To": "Saket District Centre", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Sikanderpur Metro Station Bus Stop", "To": "Guru Dronacharya", "Distance (km)": 0.7, "Time (minutes)": 5},
    {"From": "Sikanderpur Metro Station Bus Stop", "To": "DLF Phase 2", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Sikanderpur Metro Station Bus Stop", "To": "M G Road", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Sikanderpur Metro Station Bus Stop", "To": "Arjun Marg", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Guru Dronacharya", "To": "DLF Phase 2", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Guru Dronacharya", "To": "M G Road", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Guru Dronacharya", "To": "Arjun Marg", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "DLF Phase 2", "To": "M G Road", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "DLF Phase 2", "To": "Arjun Marg", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "M G Road", "To": "Arjun Marg", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Noida City Centre Terminal", "To": "Sector 34", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Noida City Centre Terminal", "To": "Sector 50", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Noida City Centre Terminal", "To": "Sector 39", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Noida City Centre Terminal", "To": "Noida Stadium", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Sector 34", "To": "Sector 50", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Sector 34", "To": "Sector 39", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Sector 34", "To": "Noida Stadium", "Distance (km)": 1.6, "Time (minutes)": 9},
    {"From": "Sector 50", "To": "Sector 39", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Sector 50", "To": "Noida Stadium", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Sector 39", "To": "Noida Stadium", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Botanical Garden Metro Station Bus Stop", "To": "Sector 37", "Distance (km)": 0.7, "Time (minutes)": 5},
    {"From": "Botanical Garden Metro Station Bus Stop", "To": "Sector 44", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Botanical Garden Metro Station Bus Stop", "To": "NTPC", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Botanical Garden Metro Station Bus Stop", "To": "Amity University", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Sector 37", "To": "Sector 44", "Distance (km)": 0.9, "Time (minutes)": 6},
    {"From": "Sector 37", "To": "NTPC", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Sector 37", "To": "Amity University", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Sector 44", "To": "NTPC", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Sector 44", "To": "Amity University", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "NTPC", "To": "Amity University", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Vishwavidyalaya Metro Station Bus Stop", "To": "University of Delhi", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Vishwavidyalaya Metro Station Bus Stop", "To": "Guru Tegh Bahadur Nagar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Vishwavidyalaya Metro Station Bus Stop", "To": "Kamla Nagar", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Vishwavidyalaya Metro Station Bus Stop", "To": "Mall Road", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "University of Delhi", "To": "Guru Tegh Bahadur Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "University of Delhi", "To": "Kamla Nagar", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "University of Delhi", "To": "Mall Road", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Guru Tegh Bahadur Nagar", "To": "Kamla Nagar", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Guru Tegh Bahadur Nagar", "To": "Mall Road", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Kamla Nagar", "To": "Mall Road", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Janakpuri West Metro Station Bus Stop", "To": "District Centre", "Distance (km)": 0.6, "Time (minutes)": 4},
    {"From": "Janakpuri West Metro Station Bus Stop", "To": "Tilak Nagar", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Janakpuri West Metro Station Bus Stop", "To": "Uttam Nagar", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Janakpuri West Metro Station Bus Stop", "To": "Vikas Puri", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "District Centre", "To": "Tilak Nagar", "Distance (km)": 0.9, "Time (minutes)": 6},
    {"From": "District Centre", "To": "Uttam Nagar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "District Centre", "To": "Vikas Puri", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Tilak Nagar", "To": "Uttam Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Tilak Nagar", "To": "Vikas Puri", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "Uttam Nagar", "To": "Vikas Puri", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Anand Vihar ISBT", "To": "Vivek Vihar", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Anand Vihar ISBT", "To": "Karkardooma", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Anand Vihar ISBT", "To": "Preet Vihar", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Anand Vihar ISBT", "To": "Patparganj", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Vivek Vihar", "To": "Karkardooma", "Distance (km)": 0.7, "Time (minutes)": 4},
    {"From": "Vivek Vihar", "To": "Preet Vihar", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Vivek Vihar", "To": "Patparganj", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Karkardooma", "To": "Preet Vihar", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Karkardooma", "To": "Patparganj", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Preet Vihar", "To": "Patparganj", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Nehru Place Metro Station Bus Stop", "To": "Kalkaji", "Distance (km)": 0.7, "Time (minutes)": 4},
    {"From": "Nehru Place Metro Station Bus Stop", "To": "CR Park", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Nehru Place Metro Station Bus Stop", "To": "GK-2", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Nehru Place Metro Station Bus Stop", "To": "East of Kailash", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Kalkaji", "To": "CR Park", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Kalkaji", "To": "GK-2", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Kalkaji", "To": "East of Kailash", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "CR Park", "To": "GK-2", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "CR Park", "To": "East of Kailash", "Distance (km)": 1.4, "Time (minutes)": 8},
    {"From": "GK-2", "To": "East of Kailash", "Distance (km)": 1.0, "Time (minutes)": 6},
    {"From": "Sadar Bazar Bus Stop", "To": "Sadar Bazar", "Distance (km)": 0.5, "Time (minutes)": 3},
    {"From": "Sadar Bazar Bus Stop", "To": "Roop Nagar", "Distance (km)": 1.2, "Time (minutes)": 7},
    {"From": "Sadar Bazar Bus Stop", "To": "Subzi Mandi", "Distance (km)": 1.4, "Time (minutes)": 9},
    {"From": "Sadar Bazar Bus Stop", "To": "Pul Bangash", "Distance (km)": 1.8, "Time (minutes)": 11},
    {"From": "Sadar Bazar", "To": "Roop Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Sadar Bazar", "To": "Subzi Mandi", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Sadar Bazar", "To": "Pul Bangash", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Roop Nagar", "To": "Subzi Mandi", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Roop Nagar", "To": "Pul Bangash", "Distance (km)": 1.5, "Time (minutes)": 9},
    {"From": "Subzi Mandi", "To": "Pul Bangash", "Distance (km)": 1.1, "Time (minutes)": 7},
    {"From": "Sadar Bazar", "To": "Roop Nagar", "Distance (km)": 0.8, "Time (minutes)": 5},
    {"From": "Sadar Bazar", "To": "Subzi Mandi", "Distance (km)": 1.3, "Time (minutes)": 8},
    {"From": "Sadar Bazar", "To": "Pul Bangash", "Distance (km)": 1.6, "Time (minutes)": 10},
    {"From": "Roop Nagar", "To": "Subzi Mandi", "Distance (km)": 0.9, "Time (minutes)": 5},
    {"From": "Roop Nagar", "To": "Pul Bangash", "Distance (km)": 1.5, "Time (minutes)": 9},
]

# Specify the CSV file name
csv_file = 

# Specify the column headers
fieldnames = ['From', 'To', 'Distance (km)', 'Time (minutes)']

# Writing to the CSV file
with open(csv_file, mode='w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    
    # Writing the header
    writer.writeheader()
    
    # Writing the data rows
    for row in data:
        writer.writerow(row)

print(f"Data has been successfully written to {csv_file}")
